
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const FILTER_NAME = 'FILTER_NAME'
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL'
export const ORDER_BY_CONTINENT = 'ORDER_BY_CONTINENT'
export const GET_ACTIVITIES = 'GET_ACTIVITIES'
export const ORDER_BY_ACTIVITY = 'ORDER_BY_ACTIVITY'
export const ORDER_BY_SORT = 'ORDER_BY_SORT'
export const CREATE_ACTIVITY = "CREATE_ACTIVITY"